# Generated by Django 3.0.1 on 2019-12-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_rate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulse_rate',
            name='fc_high',
            field=models.FloatField(default=0, verbose_name='下限周波数'),
        ),
        migrations.AddField(
            model_name='pulse_rate',
            name='fc_low',
            field=models.FloatField(default=10, verbose_name='上限周波数'),
        ),
    ]
